### ISSUE TITLE
Single image broken manifest?

### ISSUE THREAD

**Issue by glenrobson** [mekarpeles/ia-iiif#105]
While doing the collection development I tried to create this manifest:

http://192.168.1.64:8080/iiif/3/fbf_3chords_1_/manifest.json

and it failed due to the book reader failing to return a list of files:

https://ia801604.us.archive.org/BookReader/BookReaderJSIA.php?id=fbf_3chords_1_&itemPath=/18/items/fbf_3chords_1_&server=ia801604.us.archive.org&format=jsonp&subPrefix=fbf_3chords_1_

Is this because this is a single image item? 

Item: [https://archive.org/details/fbf_3chords_1_](https://archive.org/details/fbf_3chords_1_)

Metadata: [https://archive.org/metadata/fbf_3chords_1_](https://archive.org/metadata/fbf_3chords_1_)

**Comment by glenrobson** [comment]
It looks like this was originally a PDF. The jp2s are derivative:

```
{
          "name": "3chords(1)_jp2.zip",
          "source": "derivative",
          "format": "Single Page Processed JP2 ZIP",
          "original": "3chords(1).pdf",
          "mtime": "1682356356",
          "size": "71073",
          "md5": "d512d45e9cf8c42334a6dacb4380b903",
          "crc32": "047b6f9a",
          "sha1": "2479130267c982f68b009e044dba827381011c52",
          "filecount": "1"
    },
```

**Comment by hadro** [comment]
This is now fixed, thanks Glen!
