### ISSUE TITLE
Video manifest

### ISSUE THREAD

**Issue by glenrobson** [mekarpeles/ia-iiif#108]
Comments on current iteration in:

https://github.com/ArchiveLabs/iiif.archivelab.org/pull/107

Single video gist: https://gist.github.com/digitaldogsbody/f334ccda5369cf0dc4c2c8cbfa104cbf

Multiple video gist: https://gist.github.com/digitaldogsbody/ea73b6d621f22bc88b8b353a34e9337f

**Comment by glenrobson** [comment]
Post conference:
- [x] Choice of video 
- [ ] Thumbnail
- [ ] Poster canvas 
 
 
Currently it picks the original file with MPEG4 format (as this is what is in both fixtures) for what goes on the canvas. We should look at how we handle this, as maybe the derivative MPEG4 labeled with ".ia.mp4" is more standard regardless of the source format?

**Comment by hadro** [comment]
I've been doing some testing with a [basic video manifest](https://archivelabs-iiif-archivelab-org-presentation-v3.ux-fnf-misc.archive.org/iiif/3/youtube-7w8F2Xi3vFw/manifest.json).

Seems to work just fine in UV, Ramp, and Aviary:
- [UV](https://uv-v3.netlify.app/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Farchivelabs-iiif-archivelab-org-presentation-v3.ux-fnf-misc.archive.org%2Fiiif%2F3%2Fyoutube-7w8F2Xi3vFw%2Fmanifest.json)
- [Ramp](https://iiif-react-media-player.netlify.app//?iiif-content=https%3A%2F%2Farchivelabs-iiif-archivelab-org-presentation-v3.ux-fnf-misc.archive.org%2Fiiif%2F3%2Fyoutube-7w8F2Xi3vFw%2Fmanifest.json)
- [Aviary](https://iiif.aviaryplatform.com/player?manifest=https://archivelabs-iiif-archivelab-org-presentation-v3.ux-fnf-misc.archive.org/iiif/3/youtube-7w8F2Xi3vFw/manifest.json)

The same manifest doesn't play in either Mirador or Clover; the console for both seems to refer to CORS issues, but I'm not sure how that's possible if the players above are able to begin playback on the video item without issue?

- [Mirador](https://projectmirador.org/embed/?iiif-content=https://archivelabs-iiif-archivelab-org-presentation-v3.ux-fnf-misc.archive.org/iiif/3/youtube-7w8F2Xi3vFw/manifest.json)
- [Clover](https://samvera-labs.github.io/clover-iiif/?iiif-content=https%3A%2F%2Farchivelabs-iiif-archivelab-org-presentation-v3.ux-fnf-misc.archive.org%2Fiiif%2F3%2Fyoutube-7w8F2Xi3vFw%2Fmanifest.json)

CC @saracarl @benwbrum in case this overlaps with your own testing

**Comment by glenrobson** [comment]
I wonder if @mathewjordan could let us know if we need to set CORS headers on AV material. Are there different JS methods for working with AV, some that require CORS and some that don't?

**Comment by mathewjordan** [comment]
> I wonder if @mathewjordan could let us know if we need to set CORS headers on AV material. Are there different JS methods for working with AV, some that require CORS and some that don't?

I'll take a look to see if I can figure out why this is the case with this Manifest and its resource. The big differentiating factor might be that Mirador and Clover handroll their video element while Aviary, Ramp, (video.js) and UV (mediaelement.js) utilize some helper libraries to assist -- so I'll start there and see what I can dig up.

**Comment by benwbrum** [comment]
@glenrobson to test and consider moving to production if it's still a problem.

**Comment by glenrobson** [comment]
Glen to test if this is still an issue with the live service .

**Comment by glenrobson** [comment]
Production links:

* Manifest: https://iiif.archive.org/iiif/3/youtube-7w8F2Xi3vFw/manifest.json
* [UV](https://uv-v3.netlify.app/#?c=&m=&s=&cv=&manifest=https://iiif.archive.org/iiif/3/youtube-7w8F2Xi3vFw/manifest.json)
* [Ramp](https://iiif-react-media-player.netlify.app//?iiif-content=https://iiif.archive.org/iiif/3/youtube-7w8F2Xi3vFw/manifest.json)
* [Aviary](https://iiif.aviaryplatform.com/player?manifest=https://iiif.archive.org/iiif/3/youtube-7w8F2Xi3vFw/manifest.json)
* [Mirador](https://projectmirador.org/embed/?iiif-content=https://iiif.archive.org/iiif/3/youtube-7w8F2Xi3vFw/manifest.json)
* [Clover](https://samvera-labs.github.io/clover-iiif/?iiif-content=https://iiif.archive.org/iiif/3/youtube-7w8F2Xi3vFw/manifest.json)

**Comment by glenrobson** [comment]
It looks like everything works but Clover now. Clover still seems to say there is a CORS error. I'm closing this issue and opening on on the Clover Repo but can create a new issue on the IA repo if it is something on their end:

https://github.com/samvera-labs/clover-iiif/issues/167
