### ISSUE TITLE
Broken image in cantaloupe

### ISSUE THREAD

**Issue by glenrobson** [mekarpeles/ia-iiif#114]
I suspect this is a problematic image but the following URL gives unsupported image format:

https://services-ia-iiif-cantaloupe-experiment.dev.archive.org/iiif/2/opencontext-22-e-2-203-4-1-p-3jpg%2f22-e-2-203-4-1-p-3jpg.JPG/info.json

The image is identified as:

```
file /tmp/22-e-2-203-4-1-p-3jpg.JPG 
/tmp/22-e-2-203-4-1-p-3jpg.JPG: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=9, manufacturer=Canon, model=Canon EOS DIGITAL REBEL, orientation=lower-left, xresolution=160, yresolution=168, resolutionunit=2, datetime=2007:06:30 07:34:21], baseline, precision 8, 3072x2048, components 3
```

Details: https://archive.org/details/opencontext-22-e-2-203-4-1-p-3jpg

**Comment by glenrobson** [comment]
Manifest: https://iiif.archive.org/iiif/3/opencontext-22-e-2-203-4-1-p-3jpg/manifest.json

**Comment by glenrobson** [comment]
Live image URL: https://iiif.archive.org/image/iiif/2/opencontext-22-e-2-203-4-1-p-3jpg%2f22-e-2-203-4-1-p-3jpg.JPG/info.json

**Comment by benwbrum** [comment]
This is still a problem, possibly with Cantaloupe

**Comment by glenrobson** [comment]
Transfering to: https://github.com/internetarchive/iiif/issues/55
