### ISSUE TITLE
Caching Manifests

### ISSUE THREAD

**Issue by glenrobson** [mekarpeles/ia-iiif#115]
It would be useful to cache manifests especially for large manifests like this one:

https://archivelabs-iiif-archivelab-org-presentation-v3.ux-fnf-misc.archive.org/iiif/3/mms_metcalf_box_002/manifest.json

This could be done at the python level or at the http proxy layer.

**Comment by glenrobson** [comment]
Option 1:

Key caching (with redis)
 * Time limited cache (no metadata changes will be seen until it times out)
 * Include cache parameter ```?recache=True```

Option 2:
 * http reverse proxy

**Comment by glenrobson** [comment]
Would need redis details

**Comment by glenrobson** [comment]
Can add MEM cache to the docker so that its available. 

Another option is to generate the manifest and add it to the object as a datastream.

**Comment by hadro** [comment]
Conversation 7/27:
- Add cache busting argument using Flask bypass, and then use that in the functions to bust the cache

**Comment by digitaldogsbody** [comment]
Current status (after #130 is merged):
- Basic caching on the local filesystem for all generated manifests and collections, v2 and v3
- Manifests cached for 5 days ("long")
- Collections cached for 24h ("med")
- Cache can be busted by adding `?recache=True` to a URL
