### ISSUE TITLE
Collections generation doesn't consistently work

### ISSUE THREAD

**Issue by hadro** [mekarpeles/ia-iiif#118]
I've been playing with the collections generation aspect of the v3 development work.
Many collections work just fine, like the following:

- https://archivelabs-iiif-archivelab-org-presentation-v3.ux-fnf-misc.archive.org/iiif/3/frankbford/collection.json  7,381 items, all "text")
- https://archivelabs-iiif-archivelab-org-presentation-v3.ux-fnf-misc.archive.org/iiif/3/vermontearlypostcards/collection.json (1,127 items, all "images")
- https://archivelabs-iiif-archivelab-org-presentation-v3.ux-fnf-misc.archive.org/iiif/3/middleburycollegemaps/collection.json (98 items, mix of "texts" and "images")

While others consistently return 500 internal server error:
- https://archivelabs-iiif-archivelab-org-presentation-v3.ux-fnf-misc.archive.org/iiif/3/helenhartnessflanders/collection.json (mix of AV, image, text, 1124 items)
- https://archivelabs-iiif-archivelab-org-presentation-v3.ux-fnf-misc.archive.org/iiif/3/robinsonfamilyletters/collection.json (just text items, 486 items)
- https://archivelabs-iiif-archivelab-org-presentation-v3.ux-fnf-misc.archive.org/iiif/3/middlebury-historic-texts/collection.json (1,739 items, mix of "texts" and "images")
- https://archivelabs-iiif-archivelab-org-presentation-v3.ux-fnf-misc.archive.org/iiif/3/middleburystudentactivism/collection.json (371 items, mix of text, images, audio, and movie)

I can't seem to figure out any rhyme or reason to why some work and some don't, though one consistent element is that none of the collections that have A/V items in them seem to work. That said, there are collections that have no A/V in them that also don't work, so that isn't a full explanation.

Copying @benwbrum @saracarl @glenrobson on this in case any of their testing overlaps with this

**Comment by hadro** [comment]
Ok, digging a bit more, this seems to be failing here: 
https://github.com/ArchiveLabs/iiif.archivelab.org/blob/e4c0853e44e5f2234bfb0b8e0ddd69a6df32eeb0/iiify/resolver.py#L88

Basically, the non-working collections above have one or more items that are missing the `['description']` key in the metadata response.

**Comment by digitaldogsbody** [comment]
Good spot Josh - I've pushed a quick PR to check for presence of the field before attempting to add it (which is what we do with the general metadata: https://github.com/ArchiveLabs/iiif.archivelab.org/blob/presentation-v3/iiify/resolver.py#L271-L272)

**Comment by hadro** [comment]
All collections are generated now, thanks @digitaldogsbody!
