### ISSUE TITLE
Audio item has no derivatives

### ISSUE THREAD

**Issue by hadro** [mekarpeles/ia-iiif#126]
I can't say why, but this item has no audio derivatives created, which means the code logic is not generating any items for the v3 manifest: 

* Metadata: https://archive.org/metadata/kaled_jalil
* Details page: https://archive.org/details/kaled_jalil

While it's an edge case, I've seen in the help docs that it is possible for uploaders tor request that all IA-created derivatives be removed from an item, say in the case where a user only wants the lossless files they uploaded to appear as options. 

Since there are still playable files -- in this case, valid mp3s -- we should figure out how to handle this logic.

**Comment by glenrobson** [comment]
Manifest: https://iiif.archive.org/iiif/3/kaled_jalil/manifest.json (500 error)

**Comment by glenrobson** [comment]
Closed in favour of: https://github.com/internetarchive/iiif/issues/54
