### ISSUE TITLE
Mediatype "image" can have multiple images

### ISSUE THREAD

**Issue by hadro** [mekarpeles/ia-iiif#137]
See this item, for example: 

- Item page: https://archive.org/details/arkivkopia.se-lms-G70-48.3
- Metadata: https://archive.org/metadata/arkivkopia.se-lms-G70-48.3

The logic in the app resolve right now only takes the last image in the file list and creates a manifest for that single image.
We'll need a way to check for multiple valid images, and then add those as canvases individually.

**Comment by glenrobson** [comment]
Transfering to new repo: https://github.com/internetarchive/iiif/issues/52
