### ISSUE TITLE
Server failure

### ISSUE THREAD

**Issue by afarlie** [mekarpeles/ia-iiif#141]
Relaying to upstream an issue found in acessing IA's IIF service from English Wikisource.

Tjhe bug as tracked on Phabricator is:  https://phabricator.wikimedia.org/T356227

**Comment by digitaldogsbody** [comment]
There are a currently a few issues with the old ArchiveLab service. It might be worth Wikisource (and other WM sites) switching to using the new official Internet Archive IIIF service which is hosted at `iiif.archive.org` (and also has support for IIIF Presentation and Image v3 APIs).

Some info about the new service in a blog post here: https://blog.archive.org/2023/09/18/making-iiif-official-at-the-internet-archive/

**Comment by afarlie** [comment]
Noted.   So this is a 'migration' issue and thus not an actual bug.

**Comment by afarlie** [comment]
See - https://blog.archive.org/2023/09/18/making-iiif-official-at-the-internet-archive/  It's a migration issue.

**Comment by digitaldogsbody** [comment]
Yes and no - the old service _should_ still be running as there isn't currently a date set for the redirect of the old domain. There's a small bit of the old code that returns a 404 when an error happens processing an image (https://github.com/ArchiveLabs/iiif.archivelab.org/blob/master/iiify/app.py#L149-L150), so the actual issue could be a variety of things.

I've passed on a message to the IA team about the current issues with the ArchiveLab service, so hopefully it will come back to life soon :)
