### ISSUE TITLE
"502 Bad Gateway" error 

### ISSUE THREAD

**Issue by gitGalu** [mekarpeles/ia-iiif#142]
Recently, all attempts to access APIs on archivelab.org end with a "502 Bad Gateway" error.

**Comment by mekarpeles** [comment]
Should now be fixed

**Comment by gitGalu** [comment]
Thanks!
In the meantime I read that archivelab.org will be phased out, and I switched to iiif.archive.org endpoint - can I ask which endpoint/API will be the most stable one? I use it for https://github.com/gitGalu/LoboReader for checking page counts and image scan sizes as the archive.org Metadata API doesn't provide this information.
