### ISSUE TITLE
Server Failure (HTML Error 500)

### ISSUE THREAD

**Issue by afarlie** [mekarpeles/ia-iiif#144]
https://iiif.archivelab.org/iiif/jewishinterpreta00morg$267/info.json-  Gave error 500 

Migration issues?

**Comment by afarlie** [comment]
Alternatively,  please indicate exactly where the code in - https://phabricator.wikimedia.org/source/iltools/browse/main/tools/pagelister/img_links/links.py needs updating to cope with the new V3 approach.

**Comment by jcmundy** [comment]
Is there any news on this?

**Comment by glenrobson** [comment]
Hi, 

The new version 3 (and production v2) is now managed in this repo: https://github.com/internetarchive/iiif

Part of the change is the URL which now lives at iiif.archive.org. So you can change the following link in the phabricator:

```
142  'url': f'https://iiif.archivelab.org/iiif/{self.id}${iiif_index}/info.json'
```

to:

```
142: 'url': f'https://iiif.archive.org/iiif/{self.id}${iiif_index}/info.json'
```

to get to the production version 2. To get to production version 3 it is slightly more complicated as you will need to get the Image ID from the Manifest which is aviliable at:

https://iiif.archive.org/iiif/3/jewishinterpreta00morg/manifest.json

We could add a route something like iiif.archive.org/iiif/3/{id}${index}/info.json but that isn't there currently. I've created an issue (https://github.com/internetarchive/iiif/issues/79) in the ia/iiif repo. 

Also note it looks like the images aren't working for that particular item in production version 2 or version 3. I've added a issue for that here: https://github.com/internetarchive/iiif/issues/80.  

The group are next meeting in September and we can have a look at both these issues then. I'm going to close this issue but please feel free to comment on https://github.com/internetarchive/iiif/issues/79 and https://github.com/internetarchive/iiif/issues/80

Thanks

**Comment by mekarpeles** [comment]
@glenrobson I think there may still be issues with info.json endpoints. I can investigate more later this weekend

**Comment by jcmundy** [comment]
We actually use the iiif.archive.org url.  Our images aren't loading (example: https://iiif.archive.org/iiif/81285178.4931.emory.edu$3/full/full/0/default.jpg).
